owner: Georgsius
repo: status

sites:
  - name: Е-досье
    url: https://e-ecolog.ru
    icon: https://e-ecolog.ru/favicon.ico
    
  - name: Sendy
    url: https://sendy.e-ecolog.ru
    icon: https://sendy.e-ecolog.ru/img/favicon.png
        
  - name: Postal
    url: https://postal.e-ecolog.ru
    icon: https://postal.e-ecolog.ru/assets/favicon-d205a81b1f6fe6e0b46758eefd42ede8640953898d36b3016862d784b0d31e3e.png
    
  - name: Спецтранс ЖСК
    url: http://s-z.spb.ru
    icon: http://s-z.spb.ru/wp-content/uploads/2012/02/favicon.ico
    
  - name: AnyQuestion (RU)
    url: https://ru.anyquestion.info/
    icon: https://ru.anyquestion.info/favicon.ico
    
  - name: ANET
    url: https://sovet-kak.ru/
    
  - name: Wireguard Personal
    url: $WIREGUARD_PERSONAL_URL
    icon: https://www.wireguard.com/img/icons/favicon-256.png

  - name: Brain Bot
    url: https://brainbot.info/
    icon: https://brainbot.info/favicon.ico

  - name: Панель управления OpenAI
    url: $KEYS_MANAGER_URL
    icon: https://openai.com/favicon.ico


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Состояние сайтов
  introTitle: 
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
  theme: night
